const products = [
  {
    imageURL: null,
    name: 'indy fuel true wireless earbuds',
    price: 119,
    category: 'Earbuds',

    wireless: 'true',
    wirelessCharging: 'true',
    totalCharge: '30',
    waterProof: 'true',
    fullControl: 'true',
    eitherBudSolo: 'true',
    tile: 'true',
  },
  {
    imageURL: null,
    name: 'Push Ultra True wireless earbuds ',
    price: 129,
    category: 'Earbuds',
    wireless: 'true',
    wirelessCharging: 'true',
    totalCharge: '40',
    waterProof: 'true',
    fullControl: 'true',
    eitherBudSolo: 'false',
    tile: 'true',
  },
  {
    imageURL: null,
    name: ' Sesh Evo True Wireless Eabuds ',
    price: 79,
    category: 'Earbuds',
    wireless: 'true',
    wirelessCharging: 'false',
    totalCharge: '24',
    waterProof: 'true',
    fullControl: 'true',
    eitherBudSolo: 'false',
    tile: 'true',
  },
  {
    imageURL: null,
    name: 'Indy Evo True Wireless Earbuds',
    price: 199,
    category: 'Earbuds',
    wireless: 'true',
    wirelessCharging: 'false',
    totalCharge: '30',
    waterProof: 'true',
    fullControl: 'true',
    eitherBudSolo: 'true',
    tile: 'true',
  },
  {
    imageURL: null,
    name: 'Original Sesh True Wireless Earbuds with Print ',
    price: 59,
    category: 'Earbuds',
    wireless: 'true',
    wirelessCharging: 'false',
    totalCharge: '30',
    waterProof: 'true',
    fullControl: 'true',
    eitherBudSolo: 'true',
    tile: 'true',
  },
  {
    imageURL: null,
    name: ' Strong Push Ultra True Wireless Earbuds with Print  ',
    price: 129,
    category: 'Earbuds',
    wireless: 'true',
    wirelessCharging: 'true',
    totalCharge: '24',
    waterProof: 'true',
    fullControl: 'true',
    eitherBudSolo: 'true',
    tile: 'true',
  },
  {
    imageURL: null,
    name: 'Fuelbase Max Wireless Charging Pad',
    price: 59,
    category: 'Battery',
    wireless: '',
  },
  {
    imageURL: null,
    name: 'Fuelbase Wireless Charging Pad ',
    price: 39,
    category: 'Battery',
    wireless: '',
  },

  {
    imageURL: null,
    name: 'Hesh 2 Over-Ear Wireless Headphone ',
    price: 99,
    category: 'Headphone',
    wireless: 'true',
    wirelessCharging: 'false',
    totalCharge: '30',
    waterProof: 'true',
    fullControl: 'true',
    eitherBudSolo: 'true',
    tile: 'true',
  },
  {
    imageURL: null,
    name: 'Hesh 3 Wireless Over-Ear Headphone  ',
    price: 69,
    category: 'Headphone',
    wireless: 'true',
    wirelessCharging: 'false',
    totalCharge: '30',
    waterProof: 'true',
    fullControl: 'true',
    eitherBudSolo: 'true',
    tile: 'true',
  },
  {
    imageURL: null,
    name: 'Cassette Wireless On-Ear Headphones  ',
    price: 39,
    category: 'Headphone',
    wireless: 'true',
    wirelessCharging: 'false',
    totalCharge: '30',
    waterProof: 'true',
    fullControl: 'true',
    eitherBudSolo: 'true',
    tile: 'true',
  },

  {
    imageURL: null,
    name: 'Indy True Wireless Earbuds',
    price: 111,
    category: 'Earbuds',
    wireless: 'true',
    wirelessCharging: 'true',
    totalCharge: '40',
    waterProof: 'true',
    fullControl: 'true',
    eitherBudSolo: 'true',
    tile: 'true',
  },
  {
    imageURL: null,

    name: ' Crusher ANC Personalized Noise Canceling Wireless Headphones',
    price: 229,
    category: 'Headphone',
    wireless: 'true',
    wirelessCharging: 'false',
    totalCharge: '30',
    waterProof: 'true',
    fullControl: 'false',
    eitherBudSolo: 'true',
    tile: 'true',
  },
  {
    imageURL: null,
    name: 'Ink d+ Earbuds with Microphone ',
    price: 14,
    category: 'Earbuds',
    wireless: 'false',
    wirelessCharging: 'false',
    totalCharge: '0',
    waterProof: 'false',
    fullControl: 'false',
    eitherBudSolo: 'false',
    tile: 'false',
  },
  {
    imageURL: null,
    name: 'Ink d+ Wireless Earbuds  ',
    price: 40,
    category: 'Earbuds',
    wireless: 'true',
    wirelessCharging: 'false',
    totalCharge: '30',
    waterProof: 'false',
    fullControl: 'true',
    eitherBudSolo: 'true',
    tile: 'true',
  },
  {
    imageURL: null,
    name: ' Jib Earbuds with Microphone ',
    price: 19,
    category: 'Earbuds',
    wireless: 'false',
    wirelessCharging: 'false',
    totalCharge: '0',
    waterProof: 'false',
    fullControl: 'false',
    eitherBudSolo: 'false',
    tile: 'false',
  },
  {
    imageURL: null,
    name: ' Method Active Wireless Sport Earbuds',
    price: 69,
    category: 'Earbuds',
    wireless: 'true',
    wirelessCharging: 'false',
    totalCharge: '0',
    waterProof: 'false',
    fullControl: 'false',
    eitherBudSolo: 'false',
    tile: 'false',
  },
  {
    imageURL: null,
    name: 'Jib+ Wireless Earbuds  ',
    price: 59,
    category: 'Earbuds',
    wireless: 'true',
    wirelessCharging: 'false',
    totalCharge: '30',
    waterProof: 'true',
    fullControl: 'true',
    eitherBudSolo: 'false',
    tile: 'true',
  },
  {
    imageURL: null,
    name: ' Crusher Wireless Immersive Bass Headphone ',
    price: 259,
    category: 'Headphone',
    wireless: 'true',
    wirelessCharging: 'false',
    totalCharge: '30',
    waterProof: 'true',
    fullControl: 'true',
    eitherBudSolo: 'true',
    tile: 'true',
  },
  {
    imageURL: null,
    name: 'Push True Wireless Earbuds ',
    price: 69,
    category: 'Earbuds',
    wireless: 'true',
  },
  {
    imageURL: null,
    name: 'Chops Flex Sport Earbuds  ',
    price: 29,
    category: 'Earbuds',
    wireless: 'false',
    wirelessCharging: 'false',
    totalCharge: '0',
    waterProof: 'false',
    fullControl: 'false',
    eitherBudSolo: 'false',
    tile: 'false',
  },
  {
    imageURL: null,
    name: ' Riff Wireless On-Ear Headphone ',
    price: 29,
    category: 'Headphone',
    wireless: 'true',
    wirelessCharging: 'false',
    totalCharge: '30',
    waterProof: 'false',
    fullControl: 'true',
    eitherBudSolo: 'false',
    tile: 'true',
  },
  {
    imageURL: null,
    name: 'Crusher 360 Ultra-Realistic Audio   ',
    price: 299,
    category: 'Headphone',
    wireless: 'true',
    wirelessCharging: 'false',
    totalCharge: '24',
    waterProof: 'true',
    fullControl: 'true',
    eitherBudSolo: 'false',
    tile: 'true',
  },
  {
    imageURL: null,
    name: 'Sesh True Wireless Earbuds  ',
    price: 59,
    category: 'Earbuds',
    wireless: 'true',
    wirelessCharging: 'false',
    totalCharge: '24',
    waterProof: 'false',
    fullControl: 'true',
    eitherBudSolo: 'false',
    tile: 'true',
  },
  {
    imageURL: null,
    name: 'Stash Fuel 5,000 mAh Wireless Battery Pack   ',
    price: 44,
    category: 'Battery',
    wireless: '',
    wirelessCharging: 'false',
    totalCharge: '0',
    waterProof: 'false',
    fullControl: 'false',
    eitherBudSolo: 'false',
    tile: 'false',
  },
  {
    imageURL: null,
    name: ' Set In-Ear Sport Earbuds  ',
    price: 29,
    category: 'Earbuds',
    wireless: 'false',
    wirelessCharging: 'false',
    totalCharge: '0',
    waterProof: 'false',
    fullControl: 'false',
    eitherBudSolo: 'false',
    tile: 'false',
  },
  {
    imageURL: null,
    name: 'Stash Fuel 10,000 mAh Wireless Battery Pack',
    price: 79,
    category: 'Battery',
    wireless: '',
    wirelessCharging: 'false',
    totalCharge: '0',
    waterProof: 'false',
    fullControl: 'false',
    eitherBudSolo: 'false',
    tile: 'false',
  },
  {
    imageURL: null,
    name: 'Stash Mini 5,000 mAh Portable Battery Pack',
    price: 29,
    category: 'Battery',
    wireless: '',
    wirelessCharging: 'false',
    totalCharge: '0',
    waterProof: 'false',
    fullControl: 'false',
    eitherBudSolo: 'false',
    tile: 'false',
  },
  {
    imageURL: null,
    name: 'Energized Stash Mini 5,000 mAh Portable Battery Pack',
    price: 29,
    category: 'Battery',
    wireless: '',
    wirelessCharging: 'false',
    totalCharge: '0',
    waterProof: 'false',
    fullControl: 'false',
    eitherBudSolo: 'false',
    tile: 'false',
  },
  {
    imageURL: null,
    name: 'Uproar Wireless Headphone',
    price: 49,
    category: 'Headphone',
    wireless: 'true',
    wirelessCharging: 'false',
    totalCharge: '24',
    waterProof: 'false',
    fullControl: 'true',
    eitherBudSolo: 'false',
    tile: 'true',
  },
  {
    imageURL: null,
    name: 'Wild Indy Evo True Wireless Earbuds with Print',
    price: 89,
    category: 'Earbuds',
    wireless: 'true',
    wirelessCharging: 'true',
    totalCharge: '30',
    waterProof: 'true',
    fullControl: 'true',
    eitherBudSolo: 'false',
    tile: 'true',
  },
  {
    imageURL: null,
    name: 'Venue Noise Canceling Wireless Headphone',
    price: 119,
    category: 'Headphone',
    wireless: 'true',
    wirelessCharging: 'false',
    totalCharge: '30',
    waterProof: 'false',
    fullControl: 'true',
    eitherBudSolo: 'false',
    tile: 'true',
  },
  {
    imageURL: null,
    name: 'Vert Clip-Anywhere Wireless Earbuds',
    price: 69,
    category: 'Earbuds',
    wireless: 'true',
    wirelessCharging: 'true',
    totalCharge: '30',
    waterProof: 'false',
    fullControl: 'true',
    eitherBudSolo: 'true',
    tile: 'true',
  },
];

export default products;
